### PR TITLE
Now we depends on fresh telnet-client v0.7.0.

### PR DESCRIPTION
**Pull request by aborovsky**
Please, help to test my PR in all ways and merge it with your repo.

### CODE REVIEW

**Comment by phillipsnick** [comment]
Hey

I'd love to switch to the more popular `telnet-client` instead of my own fork. But it isn't really working as I'd like. The biggest problem being the chaining of requests, which your pull request on my fork fixed: https://github.com/phillipsnick/node-telnet-client/pull/9

I have an example here: https://github.com/phillipsnick/denon-avr/blob/chain-requests/examples/telnet/chain.js

Had a little play with `telnet-client v0.7.0` but I can't get multiple requests working properly.

Could you maybe put an example file in with it working?

**Comment by aborovsky** [comment]
I've fixed a lot and tested well.

Now it's working with fresh telnet-client and self-written tiny queue handling inside of [/lib/telnet.js method 'handleQueue'](https://github.com/estbeetoo/denon-avr/blob/master/lib/telnet.js)

**Comment by phillipsnick** [comment]
I like the idea, would you be able to adjust the pull request to use 2 space indentation to match the existing code?

I'll then have a proper play and see if it works with my automation system.

**Comment by aborovsky** [comment]
No problem, I'll fix identation.
Вт, 1 марта 2016 г. в 2:56, Nick Phillips notifications@github.com:

**Comment by aborovsky** [comment]
Identation and other spaces fixed!

**Pull request closed without merging**
